import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F0F0F',
  },
  accentPrimary: {
    position: 'absolute',
    top: -160,
    right: -140,
    width: 320,
    height: 320,
    borderRadius: 200,
    backgroundColor: '#1F1F1F',
    opacity: 0.6,
  },
  accentSecondary: {
    position: 'absolute',
    top: -140,
    left: -140,
    width: 300,
    height: 300,
    borderRadius: 180,
    backgroundColor: '#252525',
    opacity: 0.55,
  },
  navShell: {
    width: '100%',
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 12,
  },
  profileButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileIndicator: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#58F29A',
  },
  brandGroup: {
    alignItems: 'center',
  },
  brand: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  brandSub: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    marginTop: 2,
  },
  menuButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingBottom: 48,
    paddingTop: 24,
    gap: 24,
  },
  hero: {
    gap: 12,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  heroBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 16,
    lineHeight: 22,
  },
  scheduleCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 24,
    gap: 20,
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  scheduleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  scheduleHeading: {
    flex: 1,
    gap: 4,
  },
  scheduleTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111111',
  },
  scheduleSubtitle: {
    fontSize: 14,
    color: 'rgba(17,17,17,0.6)',
    marginTop: 4,
  },
  viewAllButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(17,17,17,0.08)',
  },
  viewAllText: {
    color: '#111111',
    fontWeight: '600',
  },
  scheduleLoading: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  scheduleEmpty: {
    paddingVertical: 24,
    alignItems: 'center',
    gap: 8,
  },
  scheduleEmptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111111',
  },
  scheduleEmptyText: {
    color: 'rgba(17,17,17,0.6)',
    textAlign: 'center',
    paddingHorizontal: 12,
    lineHeight: 20,
  },
  schedulerCta: {
    marginTop: 8,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: '#111111',
  },
  schedulerCtaText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  scheduleList: {
    gap: 16,
  },
  scheduleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  scheduleTime: {
    width: 70,
    alignItems: 'center',
    backgroundColor: '#111111',
    paddingVertical: 14,
    borderRadius: 18,
  },
  scheduleTimeDay: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    letterSpacing: 1.2,
  },
  scheduleTimeHour: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
    marginTop: 2,
  },
  scheduleInfo: {
    flex: 1,
    gap: 4,
  },
  scheduleClient: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111111',
  },
  scheduleService: {
    color: 'rgba(17,17,17,0.6)',
  },
  scheduleStatusPill: {
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
  },
  scheduleStatusText: {
    color: '#111111',
    fontWeight: '600',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  menuSheet: {
    position: 'absolute',
    top: 80,
    right: 24,
    backgroundColor: 'rgba(20,20,24,0.94)',
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 16,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 20,
  },
  menuHeader: {
    paddingBottom: 10,
    marginBottom: 4,
  },
  menuHeaderName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  menuHeaderMeta: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    marginTop: 2,
    letterSpacing: 0.4,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  menuIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuIconAccent: {
    backgroundColor: 'rgba(255,107,107,0.12)',
  },
  menuLabel: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 15,
  },
  menuLabelAccent: {
    color: '#FF6B6B',
  },
  menuDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    marginVertical: 4,
  },
  profileSheet: {
    position: 'absolute',
    top: '25%',
    alignSelf: 'center',
    width: '80%',
    maxWidth: 320,
    backgroundColor: '#181818',
    borderRadius: 28,
    padding: 24,
    alignItems: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 18 },
    elevation: 24,
  },
  profileAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  profileAvatarText: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '700',
  },
  profileName: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  profileEmail: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    textAlign: 'center',
  },
  profileRole: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 13,
  },
  profileCloseButton: {
    marginTop: 12,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
  },
  profileCloseText: {
    color: '#111111',
    fontWeight: '600',
  },
});
